### ISSUE TITLE
合法手がありません

### ISSUE THREAD

**Issue by Thagi** [pb10001/Reversi-App#4]
両者とも合法手がない場合に終わらない

**Comment by pb10005** [comment]
オセロのルールでは、両方とも置けなくなった時点で終了なので、
COMの場合・・・直前にパスがあったかどうかを記録しておき、続いた時点で終了
人間の場合・・・現状ではそもそも合法手の有無を確認していないので、確認する
で対処可能？

**Comment by Thagi** [comment]
それでよさげ
現状ポップアップが無限にわいてくるのでアプリを終了できない

**Comment by Thagi** [comment]
先攻：人間
後攻：COM
の時，ゲーム終了後1度だけ合法手がありませんが表示される

**Comment by pb10005** [comment]
思考エンジン側で合法手を判定すると実装がエンジンに依存してしまうので、GUI側で判定するか、対局を表すクラスを作って管理する(後者のほうがなんとなく良さそう)
